name: Deploy React App to AWS S3

on:
  push:
    branches:
      - dev  # Trigger workflow on 'dev' branch push

jobs:
  deploy_to_s3:
    runs-on: ubuntu-latest  # Use GitHub's Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use stable Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build  # Generates the 'build' folder

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Upload build folder to S3 Bucket
        run: |
          aws s3 sync ./build s3://zukarte-deployment-web-app --delete --exclude ".git/*"
